version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - childchain
    ports:
      - "9656:9656"
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: engine_repo
    networks: 
      - default
  childchain:
    image: omisego/childchain:latest
    command: "full_local"
    restart: always
    env_file:
      - ./localchain_contract_addresses.env
    environment:
      DATABASE_URL: postgres
      ETHEREUM_RPC_URL: http://geth:8545
      LOGGER_BACKEND: console
      ETHEREUM_EVENTS_CHECK_INTERVAL_MS: 800
    expose:
      - "9656"
    networks: 
      - default
  geth:
    image: ethereum/client-go:v1.9.13
    entrypoint: /bin/sh -c ". data/command"
    environment:
      RPC_PORT: 8545
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    volumes:
      - ./data:/data
      - ./docker/geth/command:/data/command
      - ./docker/geth/geth-blank-password:/data/geth-blank-password
    networks: 
      - default
  gencerts:
    image: alpine:3.10
    volumes:
      - "./docker/immutability/ca:/home/root/ca:rw"
      - "./docker/immutability/config:/home/root/:rw"
    entrypoint: >
      /bin/sh -c "
        apk add bash openssl
        chown -R nobody:nobody /home/root/ca && chmod -R 777 /home/root/ca
        # only gen if they aren't there
        if [ -f /home/root/ca/certs/my-service.crt ];then
          exit 0
        else
          /home/root/gencerts.sh
        fi
      "
  vault_server:
    image: omisego/immutability-vault-ethereum:latest
    networks:
      - testnet
    ports:
      - "8200:8200"
    depends_on:
      - "gencerts"
      - "geth"
    links:
      - "geth"
    volumes:
      - "./docker/immutability/ca:/home/vault/ca:rw"
      #- "./docker/immutability/ca/certs/:/etc/ssl/certs/"
      - "./docker/immutability/config:/home/vault/config:ro"
    entrypoint: >
      /bin/sh -c "
        sleep 2
        while [ ! -f /home/vault/ca/certs/my-service.crt ];do
          echo Waiting on gencerts...
          sleep 1
        done;
        /home/vault/config/entrypoint.sh
      "
    networks: 
      - default
  vault_setup:
    image: alpine:3.10
    entrypoint: >
      /bin/sh -c "
        sleep 2
        apk add curl bash jq
        sh /home/vault/config/config.sh
      "
    volumes:
      - "./docker/immutability/config:/home/vault/config:ro"
    depends_on:
      - "vault_server"
networks:
  default:
    name: childchain_default


#curl -k -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: totally-secure" -d '{"rpc_url":"http://geth:8545","chain_id":"1337"}' https://127.0.0.1:8200/v1/immutability-eth-plugin/config
