version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.pg-replica.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - childchain
    ports:
      - "9656:9656"
  postgres-0:
    image: bitnami/postgresql-repmgr:12-debian-10
    networks: 
      - default
    environment:
      - POSTGRESQL_USERNAME=omisego_dev
      - POSTGRESQL_PASSWORD=omisego_dev
      - POSTGRESQL_DATABASE=engine_repo
      - REPMGR_PASSWORD=omisego_dev
      - REPMGR_PRIMARY_HOST=postgres-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgres-0,postgres-1
      - REPMGR_NODE_NAME=postgres-0
      - REPMGR_NODE_NETWORK_NAME=postgres-0
      - REPMGR_PORT_NUMBER=5432
  postgres-1:
    image: bitnami/postgresql-repmgr:12-debian-10
    networks: 
      - default
    environment:
      - POSTGRESQL_USERNAME=omisego_dev
      - POSTGRESQL_PASSWORD=omisego_dev
      - POSTGRESQL_DATABASE=engine_repo
      - REPMGR_PASSWORD=omisego_dev
      - REPMGR_PRIMARY_HOST=postgres-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgres-0,postgres-1
      - REPMGR_NODE_NAME=postgres-1
      - REPMGR_NODE_NETWORK_NAME=postgres-1
      - REPMGR_PORT_NUMBER=5432
  childchain:
    image: omisego/childchain:latest
    command: "full_local"
    restart: always
    env_file:
      - ./localchain_contract_addresses.env
    environment:
      DATABASE_URL: nginx
      ETHEREUM_RPC_URL: http://geth:8545
      LOGGER_BACKEND: console
      ETHEREUM_EVENTS_CHECK_INTERVAL_MS: 800
    expose:
      - "9656"
    networks: 
      - default
  geth:
    image: ethereum/client-go:v1.9.13
    entrypoint: /bin/sh -c ". data/command"
    environment:
      RPC_PORT: 8545
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    volumes:
      - ./data:/data
      - ./docker/geth/command:/data/command
      - ./docker/geth/geth-blank-password:/data/geth-blank-password
    networks: 
      - default
networks:
  default:
    name: childchain_default