version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - childchain
    ports:
      - "9656:9656"
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: engine_repo
    networks: 
      - default
  childchain:
    image: omisego/childchain:latest
    command: "full_local"
    restart: always
    env_file:
      - ./localchain_contract_addresses.env
    environment:
      DATABASE_URL: postgres
      ETHEREUM_RPC_URL: http://geth:8545
      LOGGER_BACKEND: console
      ETHEREUM_EVENTS_CHECK_INTERVAL_MS: 800
    expose:
      - "9656"
    networks: 
      - default
  geth:
    image: ethereum/client-go:v1.9.15
    entrypoint: /bin/sh -c ". data/command"
    environment:
      RPC_PORT: 8545
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    volumes:
      - ./data:/data
      - ./docker/geth/command:/data/command
      - ./docker/geth/geth-blank-password:/data/geth-blank-password
    networks: 
      - default
networks:
  default:
    name: childchain_default

