version: "3.7"
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: engine_repo
  childchain:
    image: omisego/childchain:latest
    command: "full_local"
    container_name: childchain
    restart: always
    ports:
      - "9656:9656"
    env_file:
      - ./localchain_contract_addresses.env
    environment:
      DATABASE_URL: postgres
      ETHEREUM_RPC_URL: http://geth:8545
    expose:
      - "9656"
  geth:
    image: ethereum/client-go:v1.9.12
    entrypoint:
      - /bin/sh
      - -c
      - |
          # Configures geth with the deployer and authority accounts. This includes:
          #   1. Configuring the deployer's keystore
          #   2. Configuring the authority's keystore
          #   3. Configuring the keystores' password
          #   4. Unlocking the accounts by their indexes
          # CAREFUL with --allow-insecure-unlock!
          echo "" > /tmp/geth-blank-password
          # Starts geth
          # Websocket is not used by the applications but enabled for debugging/testing convenience
          geth --miner.gastarget 7500000 \
            --miner.gasprice "10" \
            --nodiscover \
            --maxpeers 0 \
            --datadir data/ \
            --syncmode 'full' \
            --networkid 1337 \
            --gasprice '1' \
            --keystore=./data/geth/keystore/ \
            --password /tmp/geth-blank-password \
            --unlock "0,1" \
            --rpc --rpcapi personal,web3,eth,net --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcport=8545 \
            --ws --wsaddr 0.0.0.0 --wsorigins='*' \
            --mine \
            --allow-insecure-unlock
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8546"
      - "8545"
    volumes:
      - ./data:/data