version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - childchain
    ports:
      - "9656:9656"
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: engine_repo
    networks:
      - default

  postgres_watcher:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    networks:
      - default

  childchain:
    image: omisego/childchain:latest
    command: "full_local"
    restart: always
    env_file:
      - ./localchain_contract_addresses.env
    environment:
      DATABASE_URL: postgres
      ETHEREUM_RPC_URL: http://geth:8545
      LOGGER_BACKEND: console
      ETHEREUM_EVENTS_CHECK_INTERVAL_MS: 800
    expose:
      - "9656"
    networks:
      - default
  geth:
    image: ethereum/client-go:v1.9.15
    entrypoint: /bin/sh -c ". data/command"
    environment:
      RPC_PORT: 8545
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    volumes:
      - ./data:/data
      - ./docker/geth/command:/data/command
      - ./docker/geth/geth-blank-password:/data/geth-blank-password
    networks:
      - default

  watcher:
    image: omisego/watcher:latest
    command: "full_local"
    container_name: watcher
    env_file:
      - ./localchain_contract_addresses.env
    environment:
      - ETHEREUM_NETWORK=LOCALCHAIN
      - ETHEREUM_RPC_URL=http://geth:8545
      - CHILD_CHAIN_URL=http://childchain:9656
      - PORT=7434
      - APP_ENV=local_docker_development
      - DD_HOSTNAME=datadog
      - DD_DISABLED=true
      - DB_PATH=/data
      - ETHEREUM_EVENTS_CHECK_INTERVAL_MS=800
      - ETHEREUM_STALLED_SYNC_THRESHOLD_MS=20000
      - ETHEREUM_BLOCK_TIME_SECONDS=1
      - EXIT_PROCESSOR_SLA_MARGIN=5520
      - EXIT_PROCESSOR_SLA_MARGIN_FORCED=TRUE
      - LOGGER_BACKEND=console
      - RELEASE_COOKIE=development
      - NODE_HOST=127.0.0.1
    restart: always
    ports:
      - "7434:7434"
    expose:
      - "7434"
    volumes:
      - ./data:/data
    healthcheck:
      test: curl watcher:7434
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    depends_on:
      - childchain
    networks:
      - default

  watcher_info:
    image: omisego/watcher_info:latest
    command: "full_local"
    container_name: watcher_info
    env_file:
      - ./localchain_contract_addresses.env
    environment:
      - ETHEREUM_NETWORK=LOCALCHAIN
      - ETHEREUM_RPC_URL=http://geth:8545
      - CHILD_CHAIN_URL=http://childchain:9656
      - DATABASE_URL=postgresql://omisego_dev:omisego_dev@postgres_watcher:5432/omisego_dev
      - PORT=7534
      - APP_ENV=local_docker_development
      - DD_HOSTNAME=datadog
      - DD_DISABLED=true
      - DB_PATH=/data
      - ETHEREUM_EVENTS_CHECK_INTERVAL_MS=800
      - ETHEREUM_BLOCK_TIME_SECONDS=1
      - EXIT_PROCESSOR_SLA_MARGIN=5520
      - EXIT_PROCESSOR_SLA_MARGIN_FORCED=TRUE
      - LOGGER_BACKEND=console
      - RELEASE_COOKIE=development
      - NODE_HOST=127.0.0.1
    restart: always
    ports:
      - "7534:7534"
    expose:
      - "7534"
    volumes:
      - ./data:/data
    healthcheck:
      test: curl watcher_info:7534
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    depends_on:
      - childchain
      - postgres
    networks:
      - default

networks:
  default:
    name: childchain_default
