version: "3.7"
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    environment:
      - POSTGRES_USER=omisegodev
      - POSTGRES_PASSWORD=omisegodev
    networks:
      chain_net:
        ipv4_address: 172.27.0.107
