version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.pg-replica.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres-0
  postgres-0:
    image: bitnami/postgresql-repmgr:12-debian-10
    networks:
      chain_net:
        ipv4_address: 172.27.0.110
    environment:
      - POSTGRESQL_USERNAME=omisego_dev
      - POSTGRESQL_PASSWORD=omisego_dev
      - POSTGRESQL_DATABASE=engine_repo
      - REPMGR_PASSWORD=omisego_dev
      - REPMGR_PRIMARY_HOST=postgres-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgres-0,postgres-1
      - REPMGR_NODE_NAME=postgres-0
      - REPMGR_NODE_NETWORK_NAME=postgres-0
      - REPMGR_PORT_NUMBER=5432
  postgres-1:
    image: bitnami/postgresql-repmgr:12-debian-10
    networks:
      chain_net:
        ipv4_address: 172.27.0.111
    environment:
      - POSTGRESQL_USERNAME=omisego_dev
      - POSTGRESQL_PASSWORD=omisego_dev
      - POSTGRESQL_DATABASE=engine_repo
      - REPMGR_PASSWORD=omisego_dev
      - REPMGR_PRIMARY_HOST=postgres-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=postgres-0,postgres-1
      - REPMGR_NODE_NAME=postgres-1
      - REPMGR_NODE_NETWORK_NAME=postgres-1
      - REPMGR_PORT_NUMBER=5432
    depends_on:
      - postgres-0
  childchain:
    environment:
      DATABASE_URL: nginx