version: 2.1
jobs:
  build:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.2
      - image: circleci/postgres:9.6.12-alpine
        environment:
          POSTGRES_USER: omisego_dev
          POSTGRES_PASSWORD: omisego_dev
          POSTGRES_DB: engine_repo_test
          CIRLCECI: true
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix do deps.get, compile --warnings-as-errors --ignore-module-conflict --force
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
            - "_build"
  test:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.2
    environment:
      MIX_ENV=test
    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix test --exclude skip --exclude integration
      - run: mix coveralls.circle
