version: 2.1
jobs:

  build:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.2
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: omisego_dev
          POSTGRES_PASSWORD: omisego_dev
          POSTGRES_DB: engine_repo_test
          CIRLCECI: true
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix do deps.get, compile --warnings-as-errors --force
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
            - "_build"
            - "dialyzer.ignore-warnings"

  test:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.2
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: omisego_dev
          POSTGRES_PASSWORD: omisego_dev
          POSTGRES_DB: engine_repo_test
          CIRLCECI: true
    environment:
      MIX_ENV=test
    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix test

  credo:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.2
    environment:
      MIX_ENV=test
    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix do credo --strict, format --check-formatted --dry-run

  dialyzer:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.2
    environment:
      MIX_ENV=dev
    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - restore_cache:
          key: v2-dialyzer-plts-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run:
          name: Unpack PLT cache
          command: |
            mkdir -p _build/dev
            cp plts/dialyxir*.plt _build/dev/ || true
            mkdir -p ~/.mix
            cp plts/dialyxir*.plt ~/.mix/ || true
      - run:
          name: Dialyzer
          command: |
            mix dialyzer
          no_output_timeout: 2400
      - run:
          name: Pack PLT cache
          command: |
            mkdir -p plts
            cp _build/dev/dialyxir*.plt plts/
            cp ~/.mix/dialyxir*.plt plts/
      - save_cache:
          key: v2-dialyzer-plts-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "plts"

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build
      - test:
          requires:
            - build
      - credo:
          requires:
            - build

      - dialyzer:
          requires:
            - build
