version: 2.1
commands:
  add_rust_to_path:
    description: "Add path to PATH env var"
    steps:
      - run:
          name: Add rust to PATH env
          command: echo 'export PATH=~/.cargo/bin/:$PATH' >> $BASH_ENV
  install_rust:
    description: "Install Rust"
    steps:
      - run:
          name: Install Rust
          command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - add_rust_to_path

jobs:
  build:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.4
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: omisego_dev
          POSTGRES_PASSWORD: omisego_dev
          POSTGRES_DB: engine_repo_test
          CIRLCECI: true
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - install_rust
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v4-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix do deps.get, compile --warnings-as-errors --force
      - save_cache:
          key: v4-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
            - "_build"
            - "~/.cargo/"

  test:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.4
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: omisego_dev
          POSTGRES_PASSWORD: omisego_dev
          POSTGRES_DB: engine_repo_test
          CIRLCECI: true
    environment:
      MIX_ENV=test
    steps:
      - add_rust_to_path
      - checkout
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v4-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix test

  integration:
    working_directory: ~/childchain
    machine:
      image: ubuntu-1604:201903-01
    environment:
      MIX_ENV=test
    steps:
      - checkout
      - install_rust
      - run: docker-compose up -d postgres
      - restore_cache:
          key: v6-asdf-install
      - run:
          name: Install Erlang and Elixir
          command: |
            [ -d ~/.asdf-vm ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf-vm --branch v0.7.8
            echo 'source ~/.asdf-vm/asdf.sh' >> $BASH_ENV
            source $BASH_ENV
            asdf update
            asdf plugin-add erlang || asdf plugin-update erlang
            asdf plugin-add elixir || asdf plugin-update elixir
            asdf install
            asdf global elixir 1.10.4-otp-23
            asdf global erlang 23.0.3
            mix local.rebar --force && mix local.hex --force
          no_output_timeout: 2400
      - save_cache:
          key: v6-asdf-install
          paths:
            - ~/.asdf
            - ~/.asdf-vm
      - run: make init-contracts
      - restore_cache:
          key: v4-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix test.integration

  test_docker_compose_release:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - install_rust
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Setup data dir
          command: |
            [ -d data ] || mkdir data && chmod 777 data
      - run: make docker-childchain
      - run:
          name: Start daemon services
          command: |
            cd priv/cabbage
            make start_daemon_services || (START_RESULT=$?; docker-compose logs; exit $START_RESULT;)
      - run:
          name: Print docker states
          command: |
            docker image ls
            docker-compose ps
      - restore_cache:
          key: v2-asdf-install
      - run:
          name: Install Erlang and Elixir
          command: |
            [ -d ~/.asdf-vm ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf-vm --branch v0.7.4
            echo 'source ~/.asdf-vm/asdf.sh' >> $BASH_ENV
            source $BASH_ENV
            cd priv/cabbage
            asdf plugin-add erlang || asdf plugin-update erlang
            asdf plugin-add elixir || asdf plugin-update elixir
            asdf install erlang 22.3
            asdf install elixir 1.10.2
            asdf global elixir 1.10.2
            asdf global erlang 22.3
            mix local.rebar --force && mix local.hex --force
          no_output_timeout: 2400
      - save_cache:
          key: v2-asdf-install
          paths:
            - ~/.asdf
            - ~/.asdf-vm
      - run: sh .circleci/status.sh
      - restore_cache:
          key: v2-mix-specs-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run:
          name: Run specs
          command: |
            cd priv/cabbage
            make install
            make generate_api_code
            mix deps.get
            mix test
      - run:
          name: (Cabbage) Format generated code and check for warnings
          command: |
            cd priv/cabbage
            # run format ONLY on formatted code so that it cleans up quoted atoms because
            # we cannot exclude folders to --warnings-as-errors
            mix format apps/child_chain_api/lib/child_chain_api/model/*.ex
            mix format apps/watcher_info_api/lib/watcher_info_api/model/*.ex
            mix format apps/watcher_security_critical_api/lib/watcher_security_critical_api/model/*.ex
            MIX_ENV=test mix do compile --warnings-as-errors --ignore-module-conflict --force, test --exclude test
      - save_cache:
          key: v2-mix-specs-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "priv/cabbage/deps"
      - run:
          name: (Cabbage) Credo and formatting
          command: |
            cd priv/cabbage
            mix do credo, format --check-formatted --dry-run

  test_docker_compose_reorg:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      REORG: true
    steps:
      - checkout
      - install_rust
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Setup data dir
          command: |
            [ -d data1 ] || mkdir data1 && chmod 777 data1
            [ -d data2 ] || mkdir data2 && chmod 777 data2
            [ -d data ] || mkdir data && chmod 777 data
      - run: make docker-childchain
      - run:
          name: Start daemon services
          command: |
            cd priv/cabbage
            make start_daemon_services_reorg || (START_RESULT=$?; docker-compose logs; exit $START_RESULT;)
      - run:
          name: Print docker states
          command: |
            docker image ls
            docker-compose ps
      - restore_cache:
          key: v2-asdf-install
      - run:
          name: Install Erlang and Elixir
          command: |
            [ -d ~/.asdf-vm ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf-vm --branch v0.7.4
            echo 'source ~/.asdf-vm/asdf.sh' >> $BASH_ENV
            source $BASH_ENV
            cd priv/cabbage
            asdf plugin-add erlang || asdf plugin-update erlang
            asdf plugin-add elixir || asdf plugin-update elixir
            asdf install erlang 22.3
            asdf install elixir 1.10.2
            asdf global elixir 1.10.2
            asdf global erlang 22.3
            mix local.rebar --force && mix local.hex --force
          no_output_timeout: 2400
      - save_cache:
          key: v2-asdf-install
          paths:
            - ~/.asdf
            - ~/.asdf-vm
      - run: sh .circleci/status.sh
      - restore_cache:
          key: v2-mix-specs-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run:
          name: Print watcher logs
          command: make cabbage-reorg-watcher-logs
          background: true
      - run:
          name: Print watcher_info logs
          command: make cabbage-reorg-watcher_info-logs
          background: true
      - run:
          name: Print childchain logs
          command: make cabbage-reorg-childchain-logs
          background: true
      - run:
          name: Print geth logs
          command: make cabbage-reorg-geth-logs
          background: true
      - run:
          name: Print reorg logs
          command: make cabbage-reorgs-logs
          background: true
      - run:
          name: Run specs
          command: |
            cd priv/cabbage
            make install
            make generate_api_code
            mix deps.get
            mix test --only reorg --trace
          no_output_timeout: 30m


  credo:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.4
    environment:
      MIX_ENV=test
    steps:
      - checkout
      - add_rust_to_path
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v4-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix do credo --strict, format --check-formatted --dry-run
      - run:
          name: "Consistent naming of TX_HASH - it's tx_hash not txhash"
          command: |
            export SHELL=/bin/bash
            set +eo pipefail
            _counter=$(grep -ri "txhash" . | grep -c "txhash")
            echo "Current occurrences of txhash:"
            echo $_counter
            if [ $_counter -gt 3 ]; then
              echo "Have you been naughty or nice? Find out if Santa knows."
              exit 1
            fi
      - run:
          name: "Consistent naming of CHILDCHAIN - it's childchain not child_chain or child-chain"
          command: |
            export SHELL=/bin/bash
            set +eo pipefail
            _counter=$(grep -ri --exclude-dir=./priv/cabbage "child_chain" . | grep -vi -e "child_chain_api" -e "child_chain_url" | grep -c "child_chain")
            echo "Current occurrences of child_chain:"
            echo $_counter
            if [ $_counter -gt 12 ]; then
              echo "Have you been naughty or nice? Find out if Santa knows."
              exit 1
            fi
            _counter=$(grep -ri "child-chain" . | grep -c "child-chain")
            echo "Current occurrences of child-chain:"
            echo $_counter
            if [ $_counter -gt 4 ]; then
              echo "Have you been naughty or nice? Find out if Santa knows."
              exit 1
            fi

  dialyzer:
    working_directory: ~/childchain
    docker:
      - image: circleci/elixir:1.10.4
    environment:
      MIX_ENV=dev
    steps:
      - checkout
      - install_rust
      - run: mix local.rebar --force && mix local.hex --force
      - restore_cache:
          key: v4-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - restore_cache:
          key: v1-dialyzer-plts-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run:
          name: Unpack PLT cache
          command: |
            mkdir -p _build/dev
            cp plts/dialyxir*.plt _build/dev/ || true
            mkdir -p ~/.mix
            cp plts/dialyxir*.plt ~/.mix/ || true
      - run:
          name: Dialyzer
          command: |
            mix dialyzer
          no_output_timeout: 2400
      - run:
          name: Pack PLT cache
          command: |
            mkdir -p plts
            cp _build/dev/dialyxir*.plt plts/
            cp ~/.mix/dialyxir*.plt plts/
      - save_cache:
          key: v1-dialyzer-plts-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "plts"

  publish_childchain:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      CHILDCHAIN_IMAGE_NAME: "omisego/childchain"
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make docker-childchain CHILDCHAIN_IMAGE_NAME=$CHILDCHAIN_IMAGE_NAME
      - run: IMAGE_NAME=$CHILDCHAIN_IMAGE_NAME sh .circleci/ci_publish.sh

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build
      - test:
          requires:
            - build

      - integration:
          requires:
            - build

      # - test_docker_compose_release:
      #     requires:
      #       - build
      #
      # - test_docker_compose_reorg:
      #     requires:
      #       - build

      - credo:
          requires:
            - build

      - dialyzer:
          requires:
            - build

      - publish_childchain:
          requires:
            [
              dialyzer,
              credo,
              integration,
              test,
              build
            ]
          filters: &master_and_version_branches_and_all_tags
            branches:
              only:
                - master
                # vMAJOR.MINOR (e.g. v0.1, v0.2, v1.0, v2.1, etc.)
                - /^v[0-9]+\.[0-9]+/
            tags:
              only:
                - /.+/
