Application.start(:sasl)
Mix.Task.run("ecto.drop", ~w(--quiet))
Mix.Task.run("ecto.create", ~w(--quiet))
Mix.Task.run("ecto.migrate", ~w(--quiet))
{:ok, _ecto} = Application.ensure_all_started(:ecto)
{:ok, _ecto_sql} = Application.ensure_all_started(:ecto_sql)
{:ok, _postgrex} = Application.ensure_all_started(:postgrex)
{:ok, _db_connection} = Application.ensure_all_started(:db_connection)
{:ok, _} = Engine.Repo.start_link([])
ExUnit.start(capture_log: true, assert_receive_timeout: 1000, exclude: [integration: true])
